# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('internet', models.BooleanField(default=False)),
                ('area', models.CharField(max_length=100)),
                ('bedroom', models.PositiveIntegerField()),
                ('bathroom', models.CharField(choices=[('Shared', 'Shared'), ('Private', 'Private')], max_length=100)),
                ('water_supply', models.CharField(choices=[('Limited', 'Limited'), ('24hrs Supply', '24hrs Supply')], max_length=100)),
                ('furnished', models.CharField(choices=[('Well-Furnished', 'Well-Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('None', 'None')], max_length=100)),
                ('mininun_stay', models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('More', 'More')], max_length=100)),
                ('utilities_cost', models.CharField(choices=[('Included', 'Included'), ('Excluded', 'Excluded')], max_length=100)),
                ('parking', models.BooleanField(default=False)),
                ('rent', models.PositiveIntegerField()),
                ('max_occupency', models.CharField(choices=[('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5')], max_length=100)),
                ('apartment_avaibility', models.BooleanField(default=False)),
                ('kitchen', models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared')], max_length=100)),
                ('favorites', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_image', models.ImageField(null=True, upload_to='media/apartment_image')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filter.City'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
